### ISSUE TITLE
GetText gets corrupted

### ISSUE THREAD

**Issue by gucio321** [cimgui/cimCTE#6]
Hi,
I think that for some strange memory things, data returned by GetText in my wrapper, get scorrupted.
This change fixes that issue:
```cpp
    std::string str = self->GetText();
    char* cStr = new char[str.size() + 1]; // Allocate memory
    std::strcpy(cStr, str.c_str()); // Copy string contents
    return cStr; // Return new C-style string
```

**Comment by sonoro1234** [comment]
It depends on what you do with returned const char*. 
It should not be modified. And should be used before string value (editor content) is modified, never afterwards. 
If you need to modify it or use it after editor content is changed, do the copy yourself.

**Comment by gucio321** [comment]
@sonoro1234 according to [this thread](https://stackoverflow.com/questions/22330250/how-to-return-a-stdstring-c-str)
this pointer is automatically destroyed as soon as std::string instance (editor->GetText) is destroyed. In case of this function that probably means immedate destruction of editor->GetText() std::string instance so also `char*` returned by `c_str()`

This copy trick is imo required to make it work at all

**Comment by sonoro1234** [comment]
https://github.com/sonoro1234/LuaJIT-ImGui/blob/1c5a4dcf6e13f2ac256c5aa93a04f9fc1b09a602/examples/libs/CTEwindow.lua#L157

This is my use. As you can see it is inmediately copied to a Lua string. No problems found (with no multitasking)

The other solution returns a new  pointer that should be freed by calling delete[] !!!
There is one solution with strdup() that would require to call free ...from LuaJIT or C#

**Comment by gucio321** [comment]
https://github.com/AllenDang/cimgui-go/blob/main/ImGuiColorTextEdit%2Fcimcte_funcs.go#L173

Here is my usage. The string is already corrupted when it gets to Go (but isn't in cimCTE.cpp yet)

For freeing: note that every other imgui function returns char* do it requires freeing anyway

Over that, link you've provided seems to use cpp syntax (?) (maybe it operates on std::strings)

**Comment by sonoro1234** [comment]
I am not sure about `C.GoString` making a memory copy. Could you try to copy this string before returning?


> For freeing: note that every other imgui function returns char* do it requires freeing anyway

Thats not true. Check any of those

````
nil     const char*     igImStrSkipBlank
nil     const char*     igImStrbol
nil     const char*     igImStrchrRange
nil     char*   igImStrdup
nil     char*   igImStrdupcpy
nil     const char*     igImStreolRange
nil     const char*     igImStristr
nil     const char*     igImTextCharToUtf8
nil     const char*     igImTextFindPreviousUtf8Codepoint
nil     const char*     igFindRenderedTextEnd
nil     const char*     igGetClipboardText
nil     const char*     ImFont_GetDebugName
nil     const ImWchar*  ImFontAtlas_GetGlyphRangesCyrillic
nil     const ImWchar*  ImFontAtlas_GetGlyphRangesDefault
nil     const ImWchar*  ImFontAtlas_GetGlyphRangesGreek
nil     const ImWchar*  ImFontAtlas_GetGlyphRangesJapanese
nil     const ImWchar*  ImFontAtlas_GetGlyphRangesThai
nil     const ImWchar*  ImFontAtlas_GetGlyphRangesVietnamese
nil     const char*     igGetKeyChordName
nil     const char*     igGetKeyName
nil     const char*     igTabBarGetTabName
nil     const char*     igTableGetColumnName
nil     const char*     igTableGetColumnName
nil     const char*     igGetStyleColorName
nil     const char*     igGetVersion
nil     const char*     igSaveIniSettingsToMemory
nil     const char*     ImGuiTextIndex_get_line_begin
nil     const char*     ImGuiTextIndex_get_line_end
nil     char*   ImGuiWindowSettings_GetName
nil     const char*     ImGuiTextBuffer_begin
nil     const char*     ImGuiTextBuffer_c_str
nil     const char*     ImGuiTextBuffer_end
nil     const ImWchar*  ImFontAtlas_GetGlyphRangesKorean
nil     const char*     ImFont_CalcWordWrapPositionA
nil     const char*     igImParseFormatFindEnd
nil     const char*     igImParseFormatFindStart
nil     const char*     igImParseFormatSanitizeForScanning
nil     const char*     igImParseFormatTrimDecorations
nil     const char*     igLocalizeGetMsg
nil     const ImWchar*  ImFontAtlas_GetGlyphRangesChineseSimplifiedCommon
nil     const ImWchar*  ImFontAtlas_GetGlyphRangesChineseFull

C:\LuaGL\gitsources\anima\LuaJIT-ImGui\cimgui\generator>
````
also note that free with delete[] is not the same as free with free (malloc counterpart)

> Over that, link you've provided seems to use cpp syntax (?) (maybe it operates on std::strings)

No editor:GetText is just ig.TextEditor_GetText(editor) thanks to metatypes of LuaJIT ffi. What is sure is that `ffi.string` does a copy of memory so that once used the C pointer can be freed.

**Comment by gucio321** [comment]
> I am not sure about C.GoString making a memory copy. Could you try to copy this string before returning?

yes, C.GoString returns a whole-new copy of string (the resulting string does not rely on memory allocated by C anymore). Problem is, that even if I print it just in [this place](https://github.com/AllenDang/cimgui-go/blob/main/ImGuiColorTextEdit%2Fcimcte_funcs.go#L173) it is a random characters chain so my suppose is that C frees that memory just while returning here
https://github.com/AllenDang/cimgui-go/blob/8e080c5aae4106ffd67ed4ff58be93eaf6f44d73/cwrappers/cimCTE.cpp#L214

and go can't get the right string content.

As I said in the OP, copying content of c_str fixes that issue

**Comment by sonoro1234** [comment]
> As I said in the OP, copying content of c_str fixes that issue

Yes but how do you free that memory?

for example
```cpp
CIMGUI_API const char* TextEditor_GetTextNew(TextEditor* self)
{
     std::string str = self->GetText();
    char* cStr = IM_ALLOC(str.size() + 1); // Allocate memory
    std::strcpy(cStr, str.c_str()); // Copy string contents
    return cStr; // Return new C-style string
}
CIMGUI_API void TextEditor_GetTextFree(char* ptr)
{
     IM_FREE(ptr); 
}
```
or

```cpp
CIMGUI_API const char* TextEditor_GetTextNew(TextEditor* self)
{
     std::string str = self->GetText();
    char* cStr = new char[str.size() + 1]; // Allocate memory
    std::strcpy(cStr, str.c_str()); // Copy string contents
    return cStr; // Return new C-style string
}
CIMGUI_API void TextEditor_GetTextFree(char* ptr)
{
    delete[] ptr; 
}
```

**Comment by gucio321** [comment]
My go code will be supposed to do something like this:
```go
func (self *TextEditor) Text() strng {
   return func() string {
      result := C.TextEditor_GetText(self)
      defer C.free(unsafe.Pointer(result)
      return C.GoString(result)
   }()
}
```

But it is not implemented yet (we've an issue for that atm https://github.com/AllenDang/cimgui-go/issues/366 as I've just noticed this is a problem)

**Comment by sonoro1234** [comment]
> But it is not implemented yet (we've an issue for that atm [AllenDang/cimgui-go#366](https://github.com/AllenDang/cimgui-go/issues/366) as I've just noticed this is a problem)

That what I meant. You have a memory leak. For using `C.free` memory must be allocated with malloc. Compare the two options in my previous message.

Perhaps?

```cpp
CIMGUI_API const char* TextEditor_GetTextNew(TextEditor* self)
{
     std::string str = self->GetText();
    char* cStr = malloc(str.size() + 1); // Allocate memory
    std::strcpy(cStr, str.c_str()); // Copy string contents
    return cStr; // Return new C-style string
}

```

**Comment by gucio321** [comment]
> > But it is not implemented yet (we've an issue for that atm https://github.com/AllenDang/cimgui-go/issues/366 as I've just noticed this is a problem)
>
> That what I meant. You have a memory leak. For using C.free memory must be allocated with malloc. Compare the two options in my previous message.

yesyes, I know about the leak, but does it cause my root issue? (corrupted string)

**Comment by gucio321** [comment]
oh, yeah I see, yes, I don't insist on using new char[...]. Maloc is fine for me.

**Comment by sonoro1234** [comment]
Check it and if there are no leaks or other problems I will add

```cpp
CIMGUI_API const char* TextEditor_GetTextNew(TextEditor* self)
{
     std::string str = self->GetText();
    char* cStr = malloc(str.size() + 1); // Allocate memory
    std::strcpy(cStr, str.c_str()); // Copy string contents
    return cStr; // Return new C-style string
}

```

**Comment by sonoro1234** [comment]
> yesyes, I know about the leak, but does it cause my root issue? (corrupted string)

No. The leak would be gone if you use C.free with the returned pointer. For the corrupted string use:

```cpp
CIMGUI_API const char* TextEditor_GetTextNew(TextEditor* self)
{
     std::string str = self->GetText();
    char* cStr = malloc(str.size() + 1); // Allocate memory
    std::strcpy(cStr, str.c_str()); // Copy string contents
    return cStr; // Return new C-style string
}

```
manually adding to cimCTE.cpp and cimCTE.h
and please report

**Comment by gucio321** [comment]
ok, that should work but I'll try in a sec

**Comment by gucio321** [comment]
@sonoro1234 yes, (with a small correction) it works now. Could you add it to main pls

```cpp
CIMGUI_API const char* TextEditor_GetText(TextEditor* self)
{
    std::string str = self->GetText();
    char* cStr = (char*)(malloc(str.size() + 1)); // Allocate memory
    std::strcpy(cStr, str.c_str()); // Copy string contents
    return cStr; // Return new C-style string
}
```

I just had to cast (char*)

**Comment by sonoro1234** [comment]
What if malloc returns NULL?

**Comment by gucio321** [comment]
I suppose it's a really exotic case, maybe imassert?

**Comment by sonoro1234** [comment]
We are working for imgui so that I think IM_ALLOC is the most convenient way. 
But another option is also provided (_static) that does not need to free memory althought result should be used before calling it again

```cpp
//allocates new memory that must be freed with TextEditor_GetText_free
CIMGUI_API char* TextEditor_GetText_alloc(TextEditor* self);
CIMGUI_API void TextEditor_GetText_free(char* ptr);
//returned value must be used to copy value before calling TextEditor_GetText_static again
CIMGUI_API const char* TextEditor_GetText_static(TextEditor* self);
```

```cpp
CIMGUI_API char* TextEditor_GetText_alloc(TextEditor* self)
{
    std::string str = self->GetText();
    char* cStr = (char*)IM_ALLOC(str.size() + 1); // Allocate memory
    std::strcpy(cStr, str.c_str()); // Copy string contents
    return cStr; // Return new C-style string
}
CIMGUI_API void TextEditor_GetText_free(char* ptr)
{
    IM_FREE(ptr); // free memory
}
CIMGUI_API const char* TextEditor_GetText_static(TextEditor* self)
{
    static std::string str = self->GetText();
	return str.c_str();
}
```

**Comment by sonoro1234** [comment]
See https://github.com/cimgui/cimCTE/commit/08d8e31ad1d9b80c46d31a6b458fac56c7bd7733
