### ISSUE TITLE
could you add more functions pls

### ISSUE THREAD

**Issue by gucio321** [cimgui/cimCTE#7]
Hi,
would it be possible to export the following:
- HandleKeyboardInputs
- GetSelectedText (manually wrapped - also version for _allocate like for GetText)'
- Cursor type
   - GetSelectionStart
- InsertTextAt
- SetSelection
- ScreenPosToCoordinates
- DeleteSelection
- Delete

This is not really urgent, but nice to have in my project.
For context: giu used imgui-go where this wrapper was manually writen. giu had some api and now when we've migrated to cimgui-go we'd like to cover it.

**Comment by sonoro1234** [comment]
All this methods are in `private` section of class which in cpp2ffi is deleted prior to parsing as it is plenty of C/Cpp inconveniences.
The quickest way do do it is as manual wrapping.
